AllCops:
  Include:
    - '**/Rakefile'
    - '**/*.gemspec'
    - 'exe/*'

  Exclude:
    - 'spec/fixtures/**/*'
    - 'bin/setup'
    - !ruby/regexp /old_and_unused\.rb$/

  DisplayStyleGuide: true

Metrics/MethodLength:
  Max: 30

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
